### ISSUE TITLE
Text line breaks

### ISSUE THREAD

**Issue by JamborJan** [libreboard/libreboard#124]
When crating cards the description and also the comment text don't take simple line breaks. In Edit mode they appear okay but not when the card is displayed.

Edit mode: everything ok:
![bildschirmfoto 2015-01-29 um 08 10 02](https://cloud.githubusercontent.com/assets/7508960/5953759/6514b7a8-a78e-11e4-8f9c-c19b560f3c4f.png)

Display card only:
![bildschirmfoto 2015-01-29 um 08 10 12](https://cloud.githubusercontent.com/assets/7508960/5953762/6da1cdf2-a78e-11e4-9e9e-a3bdc6cdf393.png)

**Comment by mquandalle** [comment]
This is because descriptions and comments are handled by a markdown viewer; and in the markdown "spec" you have to insert two new lines to start a new paragraph, inserting only one new line just add a space (like in HTML).

I guess we'll want to use something like github flavored markdown that handled this in a more natural way for most users.
