### ISSUE TITLE
Sandstorm.io authentication is not working

### ISSUE THREAD

**Issue by pixelport** [libreboard/libreboard#163]
How to reproduce:
1. create new sandstorm.io demo. 
2. Install Libre board. 
3. Create new Board and create a share Link with the blue "Share" button. 
4. Open Share Link in new Incognito window. 
5. Register new Libre board account ("Sign up for free"). Error: "0 must be an object [400]". 
6. Try to login with new account. User cannot access boards: "No boards.". If you go back to the shared link the user is not logged in.

Also see: http://logbot.g0v.tw/channel/sandstorm/2015-05-21#0

**Comment by kentonv** [comment]
More details: It appears LibreBoard displays its own sign-in dialog when a user other than the grain owner views the grain. Instead, it should trust Sandstorm's access control, and it should assume that anyone who arrives at the page is supposed to have access to the board (otherwise Sandstorm would have blocked them). It would actually be best to remove the accounts-password package entirely from the Sandstorm build.

**Comment by kentonv** [comment]
Also, all authentication- and authorization-related knobs should be hidden or removed from the Sandstorm build. For example, setting a board public vs. private, all of the "sign up for free" banners, etc.

**Comment by mquandalle** [comment]
The above commit fixes the issue but v0.9 still needs some work before I can release a updated spk :)

**Comment by ktersius** [comment]
Waiting for this to be fixed so we can start playing around with it.

**Comment by TiagoFreitas87** [comment]
Can you make a beta spk?
