### ISSUE TITLE
Which git respository is active, and how to ugprade to v0.8?

### ISSUE THREAD

**Issue by tonycch** [libreboard/libreboard#168]
Hi there,

First, thanks for making this great projects!

Other than github I also found git.libreboard.com, I would like to know which respository is active and more up to date?

I tried to find 0.8 but I couldn't see it in either respository. I have been using v0.71 for few weeks and would like to try the new avatar support in v0.8, where can I get it and how could I do an inplace ugprade without re-importing all cards manually?

Thanks!
Tony

**Comment by ePirat** [comment]
The git.libreboard.com repo seems to have the tags that are missing here. It think this was due to the DMCA takedown, as it seems a lot of old commits containing infringing files were removed here, for obvious reasons.

**Comment by mquandalle** [comment]
Yes the original author did include some Trello copyrighted files since the very beginning. So I had to restart the repository from scratch to remove them from the git history.

The active repository is here, on GitHub. The self-hosted gitlab instance was a temporary solution to keep the development in the open while I was removing the latest Trello files. The Gitlab instance will be disabled by the end of June.
