### ISSUE TITLE
Copyright Infringement?

### ISSUE THREAD

**Issue by nburka** [libreboard/libreboard#92]
I love open-source projects and I love Meteor.js, but I also love Trello. You can't just take the whole UI from Trello without their permission. Do you have some agreement with Fog Creek Software? Trello is definitely not open-source https://trello.com/legal and using their entire design (including their custom icon font Trellicons!) is certainly not permissible.

You can take inspiration from Trello, but you can't just steal their work. I hope this project can shift gears to honor Trello's hard work and develop your own ideas for what looks like a solid Kanban platform.

**Comment by miguelcobain** [comment]
I'm also curious on this issue, not only from a libreboard perspective but as a generic discussion.
What separates "inspiration" from "theft"?

I'm not at all claiming anything good or bad about this project. Actually, my first "gut" impression was positive, mainly because of data privacy issues and, well... freedom.

That being said, I believe there isn't any copyright infringment here. Libreboard does not use any assets, name or code from trello (possible exception for Trellicons?).

The main question I would like to ask is maybe if doing this is ethical or not.
Libreboard contributors have all the merit for this software, but when we're talking about ideas/concepts, the boundaries are bit more blurry.

**Comment by ocdtrekkie** [comment]
I definitely think it should take on it's own style, though the feature parity being so close is particularly appealing, since some people may really like Trello but need a secure on-premises solution. Changing icons is probably the most trivial of changes, and there are likely public domain or very permissively licensed icons out there that will do the job.

**Comment by Faldrian** [comment]
Please use your own style on this project... event if it would be legal to copy their style, do your own design to show them "we are not copying, we are inspired by your stuff".
I considered using this project myself, but I have a bad feedling, like using cracked software of the internet or something if I would install it as it is currently. It just feels like "I should not be allowed to use this software, because it looks like a direct rip of the original trello design".

**Comment by miguelcobain** [comment]
Is the design really that important?
What if the design is different, but the features are exactly the same?

**Comment by Faldrian** [comment]
That would definitely feel better for a start. Just don't let it look like you "stole" their whole thing and set it up as opensource project.

**Comment by tentacode** [comment]
Using years of research on design and UI / UX made by others to release a lesser clone of Trello is not a good move. I'm not a great contributor to open source project but I'm pretty sure open source isn't about that...

**Comment by Shekar73** [comment]
I have a different take on this. Open source is all about taking the best of the ideas, cloning it and  extending it. Many open source projects came forth from business side and vice versa. Using a copyright and ethical framework to describe the project in black and white terms,  does not provide justice to the nature of the work put forth to develop the project in what is turning out to be the best open source kanban project. There are many projects that  Apache Foundation maintains that are clones of big projects from Google and Facebook. If Trello is so concerned about copyright I am sure they would have come forward to complain by now. In terms of the UI,  I don't think Trello is the original creator of using cards to display information, if one goes to the screen writing board of any big TV show there will be similar interface of using cards on the walls which is no different from Trello UI. Trello might be the  original inspiration for this project in terms look and feel but then every creative endeavor is an inspiration of some thing that came before, we should all applaud the main developers for coming forward, creating this project and extending it. If the look and feel being original,  is important then this is open source people can fork it and change the look and feel like they want, no one is stopping them to do!!!

**Comment by MichaelBanks** [comment]
Libreboard are using the damn Trello logo on the top left of the page for damn's sake. At least ditch that. https://i.starbs.net/pkrK

**Comment by Narno** [comment]
I think the 2 previous reviews sums it up :)

**Comment by MichaelBanks** [comment]
Please refer to this section of Trello's legal docs http://trello.com/legal

![](https://i.starbs.net/p3DN)

I've forwarded info onto Trello who hopefully will come back with their opinions on this repo/service clone.

**Comment by mquandalle** [comment]
Thank you for opening this discussion, as the project sees (unexpected early) momentum I believe this is an issue a lot of people will raise. As one of the project co-author, let me share what I think of it, and more generally what I think of this project.

Since I haven't express my views anywhere already it's probably valuable to share a timeline overview of the project (all of this is verifiable in the git history). @yasaricli started this project at the end of January 2014 as a simple fun project, building a clone of [Trello](http://trello.com/) using the [meteor](https://www.meteor.com/) framework. At the time it was even-more a clone than today, and the project even included the Trello logo (!). He worked on it during about 10 days until “abandoning” it during the following 10 months. He resumed the work on December of last year, few days later I heard of it, was excited by the potential of an open-source Trello clone, and I decided to port the project to the [Sandstorm](http://sandstorm.io/) platform (which is a tool that let you install web applications on your own server easily). I didn't received much feedback about this port, probably because sandstorm is still a *niche* ecosystem, but because I believed in the project continued to play with it, implementing a big list of new features (*cf*. v0.7 and v0.8 of [our roadmap](http://libreboard.com/boards/MeSsFJaSqeuo9M6bs/libreboard-roadmap)) basically working full time on it for the last three weeks. And since yesterday, the project is getting popular on github.

So, copyright infringement. To be honest I think we are on the red line; but I believe we haven't crossed it. It's important to note that we write all our code, and this code is completely different from the closed source Trello code that we never have access to. I believe there is no patent protecting the Trello concepts, but I really don't know much. If someone has some stronger legal background than I do, and if he thinks we're going to jail because of this project, please share your arguments :-) I also believe that it's not in Trello Inc. interest to try to censure us because of the [Streisand effect](https://en.wikipedia.org/wiki/Streisand_effect), and it would be overly complex (I live in France, Yasar lives in Turkia, we don't have a common company or an organization, and in fact we never met each other in the real life), and even if they stop us, and because the code is distributed under the MIT license some other will take the relay (remember PopCornTime anyone?). Nevertheless I agree with you, it would be nice to have our own identity, and that's why [I asked the community for new UI ideas](https://github.com/libreboard/libreboard/issues/94), and I'll continue to work on that direction, for instance I plan to replace Trellicons by a free alternative as soon as possible (BTW the issue @MichaelBanks raised is already fixed).

But actually your critic was not only legal, but also moral. You stated that you “love Trello”, and that we “can't just steal their work” because we need “to honor Trello's hard work”, and @miguelcobain added a question “Is it ethical?”. The problem with moral and ethics is that they are context-based evaluation functions — and certainly not universal. Radical Islamist morale is maybe not the same that mine, and what a hacker think is ethical may be different that what his government thinks of it. I stand in the hackers camp. I'm the kind of person concerned by privacy violations, I never used facebook (and probably lost some friends because of that) and every time people keep asking why, I tell them how bad it is to give all you personal data to a unique private company, I also try to escape google services, and I have a PGP key. You see the kind of profile, *privacy aware* we could say. Or at least I thought I was.

With the recent interest for LibreBoard, people started registering and using the online instance we deployed on [libreboard.com](http://libreboard.com/) (both Yasar and I have access to it). With that access and a single line of bash I can connect a slightly modified version of LibreBoard (just add the `autopublish` package of meteor) to the production database; and boom, I can see what everyone is doing on any board in real time. This is just terrifying, and I didn't completely realize that before I have done this experiment. Even if most people are just testing the software, some of you seems to actually put private data in it. Yasar even received a mail from a company asking him if they can trust him with their data (!). It's even more terrifying when you realize Trello has 5 millions clients and a lot of them are putting private stuff in it (including me). Please, don't trust us with your private data, you don't need to, and it would be bad for both you and us. Feel free to use as much public boards as you want, but if you want to use a private board, keep it private (we'll help you doing that).

We are in this moment of the human history where every photo we take with our iPhone is sent to Apple, operating systems send our GPS position to Google, TV have webcam always connected to the internet, and I could continue this list as much as I want putting all the “cloud” stuff that we use a little more every days. We developers, designers, software makers, need to fight against power centralization; otherwise we'll end up in the Orwell's world — only a few decades after the roman prediction. There is a lot of work to decentralize photos, videos, messages, etc. With LibreBoard we are only doing that work for “kanban data” like projects management or personal list of people to call. A tiny piece in the grand scheme of things, but still something valuable in my opinion.

Data privacy is not the only reason I decided to spend some time and efforts on an open-source Trello clone, I also believe software developed in the open ends up being better that their closed alternatives. We plan to implement features Trello doesn't have, and in fact we already have sandstrom support (as I explained above), and localization (which is very valuable for the +90% of users that are more fluent in their native language than in English). We are going to implement more of it, and I expect the open-source community to work on plugins such as github issues synchronization (it should be easy), or LDAP integration (it should be even easier since there is already a LDAP package for the meteor user account system), or “send bitcoin to vote on a card”, and many more crazy plugin ideas I can't even think of.

So given that (1) we give you your data back, and (2) we can do better than spying alternatives, I have zero ethical problems working on this project. As we work on it, the UI similarities with Trello will decrease over time (that had begun), and this won't be an issue anymore in a month or two.

**Comment by Shekar73** [comment]
I agree :+1:

**Comment by lqtox** [comment]
The owner of Trello has shown his aversion to patents on software in general.  I don't think he would have a change of heart at this stage especially since you are actively looking for ways to differentiate from their service.

http://www.joelonsoftware.com/items/2013/07/22.html

**Comment by ocdtrekkie** [comment]
@MichaelBanks Always classy to try to drag in the lawyers while a responsible discussion is already underway. :+1: 

@mquandalle It is definitely a hard battle to fight to convince people that their data is valuable, and storing it on someone else's server is almost never for their benefit. I've discussed this with people who do not believe it's physically possible to create say... Google Now... in a manner that secures your data privately. Cloud-based businesses have made a living on changing public opinion to believe that they have users' best interests at heart, and that nothing they offer is possible on your own computers or with a methodology where they cannot read your data.

Particularly for something like a kanban board (being far from a new concept for Trello), project development info is most of the time confidential to a business, and probably one of the top things that would be great to operate internally rather than on a public host.

And I agree, as the featureset expands, and the style evolves, you'll end up with a unique product.

**Comment by ocdtrekkie** [comment]
@mquandalle You might take a look at the icon source Sandstorm is currently using. These are Creative Commons licensed, and they've available as SVG files, which are nice because they can be programmatically resized and transformed fairly easily. (I tweaked one with a pull request.)

http://thenounproject.com/naomiatkinson/uploads/

Sandstorm used another icon from a different creator at thenounproject.com as well where a suitable icon was not available in this set.

**Comment by lucasjans** [comment]
If someone can look at this product, as I did, and confuse it with Trello, that's enough for infringement. From the small screenshot on my mobile the two products look indistinguishable. 

That's a shame because there's a lot of interest in a open source Kanban product. And a lot of room to be different than Trello. It may help to look more closely at the product vision and not try to be all things it all people. From there you may find the lebse to be unique and do something original.

**Comment by willdurand** [comment]
Great answer @mquandalle, thank you!

PS: Haters gonna hate.

**Comment by mquandalle** [comment]
Since a0e1faab6802478af9f0e221fbb01234962417d3 we don't use Trellicons anymore.

**Comment by skymaiden** [comment]
I love the idea of a Trello-inspired open-source project - but it looks like you're using their CSS as well as their general design (all the same class names, all the same styles, slightly different markup)... As well as being red-line for infringement, it's not cool... Hopefully this will be fixed quickly.

**Comment by mquandalle** [comment]
We have received a DMCA takedown notice from github; it should appear [here](https://github.com/github/dmca) on the coming hours.

We are considering different solutions with @yasaricli and I'll come back in a few hours to explain what we are going to do. In the meantime, please clone the repository on your local computer so we can have a lot of copies of it. Thank you.

**Comment by willdurand** [comment]
@mquandalle you should focus on creating your own UI. That was the main issue obviously, and it should be fairly easy since Trello did not invent cards.

**Comment by aleksandar-todorovic** [comment]
@willdurand there's already tons of discussion on that happening over in the #94 .

**Comment by syrnick** [comment]
You should definitely comply with the DMCA notice. I suspect you need to learn more about the notion of copyright. You're clearly misleading users by posting an MIT license on this repository.

**Comment by danielytics** [comment]
Your lengthy reply and your "please clone the repository on your local computer so we can have a lot of copies of it" comment also sound to me like you don't really understand the issues here.

**Comment by ocdtrekkie** [comment]
@danielytics There's already an active discussion on replacing the design/styling of the app? What more, exactly, are you looking for from the devs?

**Comment by danielytics** [comment]
@ocdtrekkie I  just feel that the replies were very much trying to brush the problem away. I mean, asking people to clone because of a DMCA notice is a bit much and legally questionable. I am glad they're taking steps to replace the design because the project as a whole is very interesting and they do seem to be taking the right steps now. I wish they'd taken copyright more seriously to begin with.

**Comment by jonashaag** [comment]
> So, copyright infringement. To be honest I think we are on the red line; but I believe we haven't crossed it. It's important to note that we write all our code, and this code is completely different from the closed source Trello code that we never have access to. I believe there is no patent protecting the Trello concepts, but I really don't know much.

Coders always tend to believe that code is the most important part of a software product. It's not. Actually, for most non "high-tech" software (which Trello definitely isn't), code and code quality is one of the less important components of the product.

If you copy a product 1:1 and change the entire inner workings, but leave the design and function unmodified, then you might not have stolen the implementation part, but you have stolen the other 80% of the work put into the product.

Now, the line between "similar" (= legal) and "equal" (= stolen) is not an easy one to define. But in this case it is absolutely obvious that the way the UI was copied from Trello is *not inspiration* but *copying*, which is *not legal* anywhere in Europe or the US.

I don' t even get how this can't be clear to someone living in France or Turkey. The laws in these countries are absolutely unambiguous there.

**Comment by mquandalle** [comment]
I did not create this application, @yasaricli did. I've been working on removing Trello assets (logo, Trellicons...) from the repository because I believe this application has a lot of potential on its own. The next release will include a new UI (if you would like to help, please join #94), and in the meantime this github repository is emptied to complain with the DMCA.

**Comment by gpavlidi** [comment]
It's a well deserved DMCA. Cant expect to rip off a design of a competing closed source product, change the icons and think it's cool because you 're open sourcing it.

**Comment by orges** [comment]
When we solve the UI issues we need to follow LibreOffice license because once upon a time they were also a clone of MSoffice 98 with a diffrence, they wrote it from scratch maybe some reverse engineering... Now they have mozilla license: http://www.libreoffice.org/about-us/licenses/

**Comment by yasaricli** [comment]
Hello All,

When this issue raised in the first place, I didn't want to respond quickly, I was surprised and I waited for your comments and ideas...  First of all, i just started this project as a contribution to Meteorjs community and I am still thinking on that way...

I knew that the first version of project name "Metrello" sounds problematic but I never thought it would be problem for Trello, their mission and millions of users on that time. 

Let me summarize the timeline:

When I deploy metrello.meteor.com, I received an email from Trello, on that email they asked us to change the name and the logo and put a disclaimer that tells people "We are not affiliated, associated, authorized, endorsed by or in any way officially connected to Trello, Inc. (www.trello.com)."  

After that, we have changed the name to "Libreboard", changed the logo and put the disclaimer on our page.

Now the CSS issue is really bugging us,  If they told us in the first place we could respond quickly and do the necessary development.

And also I am really sad to see developers are talking against us just for bunch of CSS files, ignoring many kinds of effort on that project, instead of contributing us to change the UI and making it the best open source kanban board.

Sincerely yours,
Yasar

**Comment by jonashaag** [comment]
> just for bunch of CSS files

You don't get it. The CSS files are the mere implementation of months and years of research, trial and error, creative work, … This "bunch of CSS files" has cost Trello ten thousands, maybe hundreds of thousands of dollars.

How about you start a business and put five or maybe ten years of your life into building the product, and then I come by, take the CSS files that have cost you YEARS to create, and use them for my own project? That happens to be a competitor of mine?

**Comment by orges** [comment]
CSS Files are open and downloadable and yes they are work of Trello.  The main (initial) idea is a demonstration for MeteorJS, to attract contributors' attention which is not just talking but developing. If we could have this we could do it before that event occurs.
No ONE claims that LibreBoard is  a commercial product of a company called LibreBoard or any other. 
All the current effort is for developing a new UI right now.

**Comment by danielytics** [comment]
> CSS Files are open and downloadable

That is completely irrelevant. The opposition here are talking about legal and ethical issues, this is a purely technical issue with no relevance to the conversation. Being able to access and/or use something doesn't necessarily make it legal to do so.

> No ONE claims that LibreBoard is a commercial product of a company called LibreBoard or any other. 

Again, this is irrelevant. Copyright doesn't care if its for commercial purposes or not. The whole point is that the creator (Trello in this case) has the right to choose how people can use their work. The Libreboard devs used it without permission - that's the issue here, nothing else.

> All the current effort is for developing a new UI right now.

And this is a good thing! Hopefully progress will be quick and Libreboard can come back soon, because other than the copyright issue, this looks like a fantastic project and a lot of great work has went into it. Its a shame that this issue existed at all. Then again, I bet a lot more people know about this project now!

**Comment by pertrai1** [comment]
i think this project is great and wish I had forked it earlier so I could be of help to make the needed changes to accommodate the changes that are needed for this project to move forward. I look forward to this being back up again so I can use it locally on our server.

**Comment by rick** [comment]
I am not a lawyer, and this is not legal advice, but some thoughts:

 - Legally, it is difficult to pursue someone for mimicking a design. Design is generally not protected by copyright, and while there are design patents, they are fairly narrow and companies rarely file for them. The fact that Trello spent however much time and money coming up with a certain design doesn't generally give them legal rights to force someone to stop making an inspired or similar design.

 - However, the CSS files and trellicons and logo images from Trello's software **are** copyrighted. Trello are well within their legal rights to file a DMCA notice against anyone who copies those files and re-uses them without permission. That appears to be what has happened here.

 - In the case of "mytrello", Trello has a trademark interest in the name "Trello" and can use that interest to pursue the "mytrello" author legally. Trademarks, if not defended, can eventually end up unenforceable. So, Trello needs to actually protect the "Trello" mark by pursuing "mytrello" and negotiating some agreement that protects their trademark.

So: don't use someone's files or copy their code (C, Ruby, Fortran, HTML, CSS, etc.). Don't use their name. Feel free to be inspired by their design.

:bow:

**Comment by wpietri** [comment]
I second @danielytics on the notion that there is a lot of dubious justification going on here.

I suggest that it is time to apply the [First Law of Holes](http://en.wikipedia.org/wiki/First_law_of_holes). I would encourage the project owners to stop making excuses and just apologize. If I were to write one, it would go something like:

> Libreboard started out as a personal, experimental attempt to explore a JavaScript framework
> by duplicating Trello's UI. We realize now that when we shifted our aim to producing a useful
> product, we should have thrown out that experiment and started fresh. In failing to do that, we
> not only violated the law, but also appeared to be ripping off the hard work of Trello's designers
> and engineers. We deeply regret the error and apologize unreservedly to Trello. We also thank
> our fellow developers and fellow Trello fans for pointing out our errors to us. We still believe in
> the mission of Libreboard, so when it returns it will be with an interface that respects Trello's
> legal and moral rights, and one that we aim to make even better for users.

You of course should write your own. But I think things will go a lot better for your project down the road if you make a sincere apology and truly aim to do better.

**Comment by octalmage** [comment]
I think this is ridiculous. Obviously this is a work in progress and the developers didn't expect for it to get this kind of attention so fast. They are developers not designers, so they borrowed the style so they could work on what they were good at, the code. 

If anyone has a problem with the design, feel free to fork the project and submit a pull request. These guys are doing this for free and in their free time, and Trello forcing them to take it down is ugly. Trello could of just as easily commented on this issue and expressed their concerns, and I'm sure the devs would of listened. This is open source after all. 

Thank you for making this and developing a great open source alternative.

**Comment by syrnick** [comment]
I second @wpietri; I'd suggest removing any admittance of guilt just for legal reasons, but deleting the whole thing and writing an apology is the right thing to do.

I'm surprised by how many people have no understanding of copyright issues and the notion of code  license. We grew accustomed to the notion that anything on the internet can be freely used. This is NOT true. Every single sentence has an author behind it and every single line of code (including most definitely html and css) has an author and copyright holder. You can ONLY use that code if you were given permission by the copyright holder (generally the employer; occasionally the developer if not employed or can prove that they were working on personal time, personal equipment).

My advice would be to completely abandon the project and let someone start from scratch. It will be very difficult for the current authors to prove they did not use any of the copyrighted materials in their future work. Normally, a for-profit company would have hard time going after a very similar open-source clone, but in this case there's plenty of evidence that would allow the court to give Trello's lawyers access to ALL your data(code, emails, etc) related to future development of this project.

Furthermore, the possibility of legal action should raise a red flag for ANY company that would potentially use your code or your software. Many companies will not bother, but if you get included in a major project like libreoffice, you will put that project at risk. I suspect that something like libreoffice will reject your proposal after brief investigation in this incident.

P.S.: It's a bit funny commenting on a repository that will disappear after github complies with the DMCA notice. I guess, we care.
P.S.S.: I suspect, cloning a project is legally questionable. Imagine buying a car loaded with a registered stolen engine(it has a serial number) and saying, we'll just return the engine to the owner.

**Comment by ocdtrekkie** [comment]
Also, @syrnick, according to Github's DMCA policy: https://help.github.com/articles/dmca-takedown-policy/ this repo will likely not be removed. As only select files were infringing, and the author has complied with the request for their removal.

**Comment by mquandalle** [comment]
@danielytics, @wpietri, and @syrnick, I understand your point. You are asking *the authors* to apologize for having stolen Trello assets. And by “the authors” you mean Yasar and me.

I just want to emphasize that I haven't done what you are accusing me; namely ripping of Trello. The Metrello project was published by Yasar in January 2014 and included some Trello copyrighted assets (logo, trellicons, and CSS). Yasar already explained why he did that (to play with Meteor) and that he had no bad intentions.

I discovered the project 11 months later; I liked the idea of an open-source kanban board made with Meteor (I have some expertise in the framework) and I started improving it. Yasar gave me write access to his repository and put my name on the home page but I asked neither of that. 

I implemented some features Trello have (label management, board stars) and some Trello doesn't have (sandstorm, internationalization). I've also been removing Trello assets from the repository (not from the git history tough) and I'm currently working on a new UI. A lot of people are suggesting that we should just change a bit the visual aspect and return to github (which was my original plan before the DMCA, certainly a mistake of mine). I'm now getting more serious about it by working on some significant UI/UX modifications. I sincerely hope all this work will be appreciated.

**Comment by ocdtrekkie** [comment]
So, I assume going forward, to ensure DMCA compliance, the repo in the future will just have 0.9 and up?

**Comment by mquandalle** [comment]
@ocdtrekkie Absolutly

**Comment by luciotato** [comment]
>We received a DMCA takedown notice from github; it should appear here in the coming hours.

I can't find it [there](https://github.com/github/dmca)
Can you post the DMCA takedown notice ?

**Comment by pmurias** [comment]
@MichaelBanks Snitches get stitches ;)

**Comment by yasaricli** [comment]
@MichaelBanks :+1:

**Comment by centigrade-thomas-becker** [comment]
In this discussion the user @MichaelBanks is adressed a few times, but no comments from him show up. 

The account @MichaelBanks says "Joined on Jun 6, 2016" so that is probably not the original account.

I guess this issue is more or less resolved now, but can somebody please fill in the gaps?

**Comment by ocdtrekkie** [comment]
@centigrade-thomas-becker The original version of this project was much more close in style and branding to Trello. The old version was removed, retooled, eventually renamed, and is no longer materially similar to Trello in any way that copyright would affect.

**Comment by ChipWolf** [comment]
I *was* @MichaelBanks, not sure what I was discussing here though

**Comment by ChipWolf** [comment]
Looks like my comments are still there

**Comment by Michaelbanks** [comment]
Huh?? no idea whats going on tbh

**Comment by ocdtrekkie** [comment]
You have a GitHub name someone else used to have. Don't worry about it. :)

**Comment by ChipWolf** [comment]
@ocdtrekkie, no, it is me

**Comment by ChipWolf** [comment]
@Michaelbanks you registered over my old username. I'm involved in a lot of stuff, expect lots of spam.

**Comment by Michaelbanks** [comment]
So i did nothing Wrong?

**Comment by ocdtrekkie** [comment]
Nope

**Comment by samrocketman** [comment]
@Michaelbanks don't be afraid to take credit 🤣 your spam must be amazing.  I found this whole thread entertaining.  I enjoy reading about software legal issues and their resolution.  I faced growing pains with a project called enchanted keyfinder.  My case, it was quite different but I digress...

**Comment by markentingh** [comment]
I agree with @shekar73. Also, I am developing my own Trello clone in ASP.NET Core http://www.github.com/datasilk/kandu. It's fairly simple to copy the Trello design, since there really isn't much design to it. The UI is so generic, they probably can't do much about it legally against Wekan.

**Comment by ocdtrekkie** [comment]
@markentingh This is a three year old conversation that is long-since closed. Wekan wasn't even called Wekan back then, and the design has been completely rebuilt since then.

**Comment by samrocketman** [comment]
Copying and clean room implementation are completely different anyways.  Literally copied code is subject to license.  Being used as reference is not legally the same.

(This will probably be my last comment here.  Reading updates and unsubscribing.)

**Comment by xet7** [comment]
Kanban is general process development tool made by Toyota, using physical table at wall with post-it notes. There are many different software that can be used for kanban.
https://en.wikipedia.org/wiki/Kanban_(development)

Wekan does not have any UI or graphics from Trello because of original theme redesign at 2015:
https://github.com/wekan/wekan/wiki/FAQ#why-does-wekan-look-so-different-now-compared-to--v09

Wekan is original work. You can see git history with gui like gitk. Here is summary of Wekan 2 year history:
https://blog.wekan.team/2017/12/2-years-of-wekan-what-we-archieved/index.html

Trello is propietary code, it's not available anywhere publicly, only developers of Trello at Atlassian have access to Trello code. There was some Trello board where they listed what Open Source packages they use in Trello, but you can not clone Trello code repo, it's not public. Trello is only available as cloud service, you can not download Trello server, like you can download Wekan server in Docker, Ubuntu snap etc.
