### ISSUE TITLE
Attachments can be used to execute malicious files

### ISSUE THREAD

**Issue by xsuperbug** [libreboard/libreboard#99]
Merhabalar,

Dosya yükleme alanında HTML uzantısı 
filtrelenmemiş ve herhangi bir kullanıcı yetkisi olmadan bu dosyalara erişim sağlanabiliyor.

![libre](https://cloud.githubusercontent.com/assets/7601737/5857735/b32a9454-a256-11e4-9044-b5dd0a59a658.png)

Örnek  XSS saldırı vektörü aşağıdaki gibidir:
http://libreboard.com/cfs/files/attachments/XkoQT8w2ZmXGG8Ymt/test.html

**Comment by BatuhanK** [comment]
Meteor authentication tokenları localStorage'de saklanıyor, sıkıntı çıkarabilir bu durum.

Örneğin;
http://libreboard.com/cfs/files/attachments/ECPnuYtcxfk5Cb752/libre.html

**Comment by yasaricli** [comment]
@BatuhanK @xsuperbug bildirimleriniz için teşekkür ederiz. 

@xsuperbug yetki olayı public olan board larda full olması gerekiyor zaten . Yani board public ise dosyalarda erişilebilir olması gerekir. Private için ise iş listemizde şuanda. 

İş listemizde olmasının başlıca nedenide allow methodundaki userId parametresiyle alakalı bir bug 
Bilgi için https://github.com/libreboard/libreboard/blob/master/collections/attachments.js#L25 

token ve diğer önlemler içinde bir fix çıkacağız. 

tekrar teşekkür ederiz.

**Comment by mquandalle** [comment]
Thank you very much for reporting this security issue. I don't know how fluent you all are in English, but it will be really better if we can all speak a common language in our github bug tracker.

About the security issue itself, @yasaricli how did implement this feature is not currently available to work on it, so I'll take it. If I understand the issue correctly `html` files (and maybe `js` also) are interpreted in the application instead of being downloaded leading to XSS injections. Would change the mime header to `application/octet-stream` to force the browser to download the file be sufficient in this case?

**Comment by mquandalle** [comment]
Please review the security fix I released and deployed to http://libreboard.com

**Comment by yasaricli** [comment]
Thank you @mquandalle.

**Comment by xsuperbug** [comment]
Thank you @mquandalle  just checked your fix, it looks fine to me now.
